# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cdb0bee0afc454873fa81361be7f1e983d88e5c356910afdba35a9446df3803b4c950933669411a5acf5c924e86bb428f86fddf65d671549d25cf2a16f70df2e

test:
  secret_key_base: 1b9f295d1dc3b59b2fb0ee4b9fec06b80c2739af3521dbc8c0f19402df229498ad0ee4d16e640d9f7a07cdf73679c59f7938e27a14105ae415dac90cefa89f57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
